#server:
#  port: 9700
spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9700/eureka/,http://localhost:9701/eureka/,http://localhost:9702/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85

#这些---代表不同的配置文件,类似于-dev,-pre,-test
---
spring:
  profiles: 9700
server:
  port: 9700
eureka:
  instance:
    hostnam: eureka-9700

---
spring:
  profiles: 9701
server:
  port: 9701
eureka:
  instance:
    hostnam: eureka-9701

---
spring:
  profiles: 9702
server:
  port: 9702
eureka:
  instance:
    hostnam: eureka-9702






